require('core.lsp.server.lsp_clangd')
require('core.lsp.server.lsp_clojure')
--require('core.lsp.server.lsp_csharp_ls')
require('core.lsp.server.lsp_gopls')
require('core.lsp.server.lsp_pyright')
require('core.lsp.server.lsp_marksman')
-- require('core.lsp.server.lsp_omnisharp_cs')
require('core.lsp.server.lsp_powershell')
require('core.lsp.server.lsp_lua_ls')
require('core.lsp.server.lsp_roslyn')
