require("wmbat.lsp.servers.lsp_bash")
require('wmbat.lsp.servers.lsp_clangd')
require('wmbat.lsp.servers.lsp_clojure')
require('wmbat.lsp.servers.lsp_gopls')
require('wmbat.lsp.servers.lsp_pyright')
require('wmbat.lsp.servers.lsp_marksman')
-- require('wmbat.lsp.servers.lsp_powershell')
require('wmbat.lsp.servers.lsp_lua_ls')
require('wmbat.lsp.servers.lsp_roslyn')
